### ISSUE TITLE
No CDNSKEY leads to internal server error

### ISSUE THREAD

**Issue by romuald** [kalou/rrr#1]
Trying to retrieve the CDNSKEY when there is none seems to lead to an internal server error:

```
dns.resolver.NoAnswer: The DNS response does not contain an answer to the question: example.com. IN CDNSKEY
```

NoAnswer is not handled by [apply_dnssec](https://github.com/kalou/rrr/blob/master/rrr/__init__.py#L38-L53)

**Comment by kalou** [comment]
Thanks
